default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: payroll_db

test:
  <<: *default
  database: payroll_db

production:
  <<: *default
  database: payroll_db
  username: sample
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>   
